import Foundation

let UPDATE_PROFILE = "UPDATE_PROFILE"

let NOTIFICATION_SEND_TO_DRAFT = "NOTIFICATION_SEND_TO_DRAFT"
let NOTIFICATION_UPDATE_NOTIFICATION = "NOTIFICATION_UPDATE_NOTIFICATION"
let NOTIFICATION_UPDATE_PROFILE = "NOTIFICATION_UPDATE_PROFILE"
